### ISSUE TITLE
korean language pack

### ISSUE THREAD

**Issue by dutu** [altarizer/poloLender-ko#1]
Would you be interested to contribute and integrate a korean language pack into the original poloLender app?
Other vise it may be difficult to keep your separate version updated with latest features (see version 1.3.2 has been released already)

Let me know. Cheers

**Comment by altarizer** [comment]
OMG.
Sorry for late replying. 
I have not been to work for this project since i edit this project. 
Cause i did update manually including dependencies also, i chose it would not PR to your project  at that time.

I'll update korean langpack and PR asap  from latest forked version.
